### ISSUE TITLE
ARM support?

### ISSUE THREAD

**Issue by Smiggel** [Spottarr/Spottarr#63]
I tried to deploy Spottarr using the Docker stack, but get an _"Failed to deploy a stack: compose up operation failed: no matching manifest for linux/arm64/v8 in the manifest list entries"_ 

Is there not ARM CPU support for the software?

**Comment by christiaanderidder** [comment]
Hi @Smiggel,

I have pushed a linux/arm64 image under the v1.9.0-alpha.1 tag: https://github.com/Spottarr/Spottarr/pkgs/container/spottarr/460300345?tag=1.9.0-alpha.1

I don't have any native arm64 linux machine to test this on myself, but feel free to give it a try.

**Comment by Smiggel** [comment]
Thanks. I tried. I see an error in the logs:

>16:22:08 info: Microsoft.Extensions.Hosting.IHost[15242847] Database migration started [/data/spottarr.db].
16:22:13 fail: Microsoft.EntityFrameworkCore.Database.Connection[20004] An error occurred using the connection to database 'main' on server '/data/spottarr.db'.
Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool)
   at Microsoft.Data.Sqlite.SqliteConnectionPool.GetConnection()
   at Microsoft.Data.Sqlite.SqliteConnectionFactory.GetConnection(SqliteConnection outerConnection)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CreateAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at Spottarr.Data.Helpers.HostExtensions.MigrateDatabase(IHost host) in /src/src/Spottarr.Data/Helpers/HostExtensions.cs:line 20
   at Spottarr.Data.Helpers.HostExtensions.MigrateDatabase(IHost host) in /src/src/Spottarr.Data/Helpers/HostExtensions.cs:line 21
   at Program.<Main>$(String[] args) in /src/src/Spottarr.Web/Program.cs:line 20
   at Program.<Main>(String[] args)

**Comment by Smiggel** [comment]
I had a look at this topic: https://github.com/Spottarr/Spottarr/issues/59 But the suggested changes did not work. Still getting the same error.

This is my stack:
`
services:
  spottarr:
    image: ghcr.io/spottarr/spottarr:1.9.0-alpha.1
    container_name: spottarr
    user: 1000:1000 # Make sure to set the correct UID and GID for your system
    environment:
      - "USENET__HOSTNAME=***"
      - "USENET__USERNAME=***"
      - "USENET__PASSWORD=***"
      - "USENET__PORT=563"
      - "USENET__USETLS=true"
      - "USENET__MAXCONNECTIONS=10" # Adjust based on your usenet provider and other download clients
      - "SPOTNET__RETRIEVEAFTER=2006-02-21T00:00:00Z"
      - "SPOTNET__IMPORTBATCHSIZE=10000" # Adjust based on available memory
      - "SPOTNET__RETENTIONDAYS=365" # Use 0 for unlimited
      - "SPOTNET__IMPORTADULTCONTENT=false"
      - "TZ=Europe/Amsterdam" # Set your timezone, e.g. Europe/Amsterdam
    volumes:
      - ./spottarr:/data
    ports:
      - "8383:8383"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 200M # Adjust based on available memory
`

**Comment by DutchNas** [comment]
Remove ( volumes:
- ./spottarr:/data )

I had the same problem. I started with no additional additions, just a port change. As soon as I add a path, it fails. I get this error, and it won't boot. It's running on Unraid now. I just don't have a data volume and don't know where it's storage everything.

**Comment by christiaanderidder** [comment]
This is more likely to be a permission / configuration problem than an ARM (vs x64) issue. It likely either is due to incorrect permission mappings (e.g. using wrong user ID or now assigning write permissions) or some issue with the file system you are mounting (e.g. an network file share path).

To rule you any issues with Spottarr, you can just create a regular docker volume instead of a mount and see if that works without issues.

**Comment by christiaanderidder** [comment]
ARM support was added in v1.9.0.
